obj-m += ram_so1_1s2024.o
obj-m += cpu_so1_1s2024.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(shell pwd) clean
