version: '3.8'

services:
  backend:
    image: jcano21/backend
    container_name: backgo
    ports:
      - 8080:8080


  frontend:
    image: jcano21/frontend
    container_name: frontreact 
    ports: 
      - 80:80  
    depends_on:
      - backend
    

